# THIS FILE IS GENERATED BY /home/hgh/Documents/GIT/firmware/scripts/create_toolchain_binding.sh

TOOLCHAIN_DIR     := /home/hgh/Documents/GIT/firmware/output/host/bin
TOOLCHAIN_PREFIX  := arm-openipc-linux-gnueabi

TOOLCHAIN := $(TOOLCHAIN_DIR)/$(TOOLCHAIN_PREFIX)

CC := $(TOOLCHAIN)-gcc
AR := $(TOOLCHAIN)-ar
LD := $(TOOLCHAIN)-ld
RANLIB := $(TOOLCHAIN)-ranlib
NM := $(TOOLCHAIN)-nm
STRIP := $(TOOLCHAIN)-strip
