site_name: 18EV200
docs_dir: docs
site_url:
use_directory_urls: False

theme:
    name: material
    palette:
        primary: teal
        accent: deep orange
    locale: zh
    features:
        - navigation.top
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky

plugins:
    - search:
    - mkdocstrings:

nav:
    - 主页:
          - index.md
    - 环境搭建:
        - 编译: env/build.md
        - 打包: env/pack.md
    - 功能模块:
        - Task: func/fun_task.md
    - 开发者手册:
        - 网络协议:
            - MPP: net_sdk/msg_mpp.md
        - API: dev/api.md
        - SDK: dev/sdk.md
    - Q&A: qa.md
    - 关于我们: about.md
